on: [push]
name: Code analysis

jobs:
  test:
    runs-on: [medium, telia-managed, Linux, X64]
    name: check tests
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: testomatio/check-tests@stable
      with:
        framework: cypress
        tests: "./cypress/e2e/**/**.cy.js"
        token: ${{ secrets.GITHUB_TOKEN }}
        has-tests-label: true
